// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a placeholder file. Run 'protoc' to generate the actual implementation.

package proto

// EventStoreServer interface placeholder
type EventStoreServer interface {
	// TODO: Implement gRPC server interface
	// This will be generated by protoc
}

// RegisterEventStoreServer placeholder
func RegisterEventStoreServer(s interface{}, srv EventStoreServer) {
	// TODO: Implement server registration
	// This will be generated by protoc
}
